"""Hand-computed tests for the wtclient grid backtest engine port.

Every expectation below was derived by hand from the engine rules (ported
verbatim from ``browser-debug/wt-backtest.mjs``, the parity-verified Node
reference of the configurator's client-side engine). Fixtures use step 25%
because 1.25 is exact in binary floats, so the geometric level walk
(100 -> 125 -> 156.25 -> ...) is free of float-precision traps: a 10% step
lands on 110.00000000000001 and changes which levels the loop emits.
Constants carry deriving comments — they were NOT generated by running the
engine.
"""
from __future__ import annotations

import unittest

from wtclient.backtest import build_input, run_backtest, summary
from wtclient.clients.grid import GridClient

T0 = 1_700_000_000_000
STEP_MS = 900_000  # 15m


def candle(i, high, low, close):
    return {"timestamp": T0 + i * STEP_MS, "high": high, "low": low, "close": close, "open": close, "volume": 1}


# Levels for low=100, high=160, step=25%: walk 100 -> 125 (28% remain >= 25%),
# 156.25 (2.4% remain < 25% -> stop), then append high 160:
#   [100, 125, 160]
LEVELS = [100.0, 125.0, 160.0]


def base_cfg(**over):
    cfg = {
        "exchangeCode": "TEST",
        "pairCode": "PAIR",
        "gridType": "interval",
        "gridTradingType": "long",
        "gridPercentStep": 0.25,  # decimal -> engine percent 25
        "amountPerTrade": 10,
        "midPrice": 125,
        "lowPrice": 100,
        "highPrice": 160,
        "decimalsQty": 4,
    }
    cfg.update(over)
    return cfg


class TestOneRoundTripFee(unittest.TestCase):
    """One long open (down-cross at 125) + close (up-cross of 160).

    Hand trace (D=110 start, bracket C=0/_=1):
    - c1 up-candle [109, 127, 126]: crosses 125 upward -> no open (long
      grids buy down-crossings); D ends 126, pointers C=1/_=2.
    - c2 down-candle [127.5, 119, 120]: crosses 125 downward from D=127.5
      -> canOpenLong: level 125 < prev 127.5 -> OPEN LONG at 125.
    - c3 up-candle [120.5, 161.5, 161]: crosses 125 up (no close: the long
      is AT 125, close checks the level BELOW the crossed one), then
      crosses 160 up -> closes the long from 125: (160-125)/125 - 0.002
      = 0.25 - 0.002 = 0.278 = 27.8%. Edge level 160 itself cannot open.
    """

    CANDLES = [
        candle(0, 111, 109, 110),   # start bracket D=110 (100 < 110 <= 125)
        candle(1, 127, 109, 126),   # up (110 < 126)
        candle(2, 127.5, 119, 120),  # down: opens long @ 125
        candle(3, 161.5, 120.5, 161),  # up: closes long @ 160 (+27.8% w/ fee)
    ]

    def test_round_trip(self):
        result = run_backtest(base_cfg(), self.CANDLES)
        self.assertEqual(result["gridLevels"], LEVELS)
        self.assertEqual(result["gridLevelsQty"], 3)
        # realized: (160-125)/125 - 0.002 = 0.278 -> 27.8%, x10 amount = 2.78
        self.assertEqual(result["pnl"], 27.8)
        self.assertEqual(result["pnlFiat"], 2.78)
        self.assertEqual(result["positionsLong"], 1)
        self.assertEqual(result["positionsShort"], 0)
        self.assertEqual(result["unrealizedPositionsLong"], 0)
        self.assertEqual(result["unrealizedPnl"], 0)
        self.assertEqual(result["totalResult"], 27.8)
        self.assertEqual(result["totalResultFiat"], 2.78)
        # one OL @125 + one CL @160
        self.assertEqual(result["tradesCount"], 2)
        self.assertEqual(
            [(t["strategy"], round(t["price"], 6)) for t in result["trades"]],
            [("long", 125.0), ("long", 160.0)],
        )
        # edge levels never open: no trade happened at the bottom edge 100
        self.assertTrue(all(t["price"] != 100.0 for t in result["trades"]))

    def test_summary_shape(self):
        result = run_backtest(base_cfg(), self.CANDLES)
        s = summary(result)
        self.assertEqual(s["totalResult"], 27.8)
        self.assertEqual(s["positionsLong"], 1)
        self.assertEqual(s["gridLevelsQty"], 3)
        self.assertEqual(s["tradesCount"], 2)


class TestPureUptrendAllZero(unittest.TestCase):
    """LONG grid without pump protection buys down-crossings only.

    A price path that enters from below and never dips below a level buys
    nothing -> all-zero backtest (documented platform behavior).
    """

    CANDLES = [
        candle(0, 111, 109, 110),
        candle(1, 124, 110.5, 123),
        candle(2, 130, 122, 129),
    ]

    def test_all_zero(self):
        result = run_backtest(base_cfg(), self.CANDLES)
        self.assertEqual(result["pnl"], 0)
        self.assertEqual(result["unrealizedPnl"], 0)
        self.assertEqual(result["totalResult"], 0)
        self.assertEqual(result["positionsLong"], 0)
        self.assertEqual(result["unrealizedPositionsLong"], 0)
        self.assertEqual(result["tradesCount"], 0)


class TestPumpProtectionFlip(unittest.TestCase):
    """pumpProtection flips the side filter: longs open on up-crossings.

    Hand trace: c1 up-candle [109, 127, 126] crosses 125 upward with D=109
    -> with pump, canOpenLong requires level > prev price (125 > 109) ->
    OPEN LONG at 125 on the UP-cross. The drift down to 120 leaves it
    open; final close 120 marks it unrealized: (120-125)/125 = -4%.
    """

    CANDLES = [
        candle(0, 111, 109, 110),
        candle(1, 127, 109, 126),  # up: opens long @ 125 (pump flip)
        candle(2, 127.5, 119, 120),  # drift down: stays open
    ]

    def test_open_on_up_cross(self):
        result = run_backtest(base_cfg(pumpProtection=True), self.CANDLES)
        self.assertEqual(result["positionsLong"], 0)
        self.assertEqual(result["unrealizedPositionsLong"], 1)
        # (120-125)/125 = -4% exactly after rounding
        self.assertEqual(result["unrealizedPnl"], -4.0)
        self.assertEqual(result["totalResult"], -4.0)
        opens = [t for t in result["trades"] if t["strategy"] == "long" and t["side"] == "long"]
        self.assertEqual(len(opens), 1)
        self.assertEqual(round(opens[0]["price"], 6), 125.0)
        # the open happened during candle 1 (the up-cross), not candle 2
        self.assertEqual(opens[0]["timestamp"], (T0 + STEP_MS) / 1e3)


class TestNeutralMidRule(unittest.TestCase):
    """Neutral grids: longs at-or-below mid, shorts strictly above mid.

    Levels [100, 125, 156.25, 200] (low=100, high=200, step 25%), mid=125.
    Hand trace:
    - c2 crosses 125 downward from D=126.5 -> open LONG at 125 (125 <= mid).
    - c3 crosses 125 up (no open, no close — close checks the level below),
      then crosses 156.25 up -> closes the long at 156.25 (+24.8%) and
      opens SHORT at 156.25 (156.25 > mid) on the same up-cross.
    - final close 161: short unrealized = -(161-156.25)/156.25 = -3.04%.
    """

    CANDLES = [
        candle(0, 111, 109, 110),
        candle(1, 127, 109, 126),
        candle(2, 126.5, 118, 120),  # down: opens long @ 125
        candle(3, 161.5, 120.5, 161),  # up: close @156.25 (+24.8%), open short @156.25
    ]

    CFG = base_cfg(gridTradingType="neutral", lowPrice=100, highPrice=200, midPrice=125)

    def test_neutral_both_sides(self):
        result = run_backtest(self.CFG, self.CANDLES)
        self.assertEqual(result["gridLevels"], [100.0, 125.0, 156.25, 200.0])
        self.assertEqual(result["positionsLong"], 1)  # closed @156.25
        # (156.25-125)/125 - 0.002 = 0.248 -> 24.8%
        self.assertEqual(result["pnl"], 24.8)
        self.assertEqual(result["pnlFiat"], 2.48)
        self.assertEqual(result["unrealizedPositionsShort"], 1)  # open @156.25
        # -(161-156.25)/156.25*100 = -3.04
        self.assertEqual(result["unrealizedPnl"], -3.04)
        # 24.8 + (-3.04) = 21.76
        self.assertEqual(result["totalResult"], 21.76)
        self.assertEqual(result["totalResultFiat"], 2.176)


class TestStopOnOutOfGrid(unittest.TestCase):
    """stopOnOutOfGrid trims candles up to the LAST one outside the channel.

    The trim scans from the end and keeps the suffix after the highest-index
    candle that is not fully inside — so leading excursions vanish and the
    sim is equivalent to the trimmed core. A not-inside candle ANYWHERE
    (with only one following candle) drops the window below two candles and
    yields the empty result.
    """

    CORE = [
        candle(0, 111, 109, 110),
        candle(1, 127, 109, 126),
        candle(2, 127.5, 119, 120),  # opens long @ 125
    ]

    def test_leading_trim_is_equivalent(self):
        with_leading = [
            candle(-2, 170, 99, 160),  # outside (above channel)
            candle(-1, 168, 101, 158),  # not fully inside -> trims here
            *self.CORE,
        ]
        plain = run_backtest(base_cfg(), self.CORE)
        trimmed = run_backtest(base_cfg(stopOnOutOfGrid=True), with_leading)
        for key in ("pnl", "pnlFiat", "positionsLong", "unrealizedPnl", "totalResult"):
            self.assertEqual(plain[key], trimmed[key], key)
        # dateStarted is computed BEFORE the trim (first original candle)
        self.assertNotEqual(plain["dateStarted"], trimmed["dateStarted"])

    def test_too_few_candles_after_trim(self):
        # the break candle (low 99) is not fully inside; only one candle
        # follows it -> window < 2 -> empty result
        candles = [
            candle(0, 111, 109, 110),
            candle(1, 127, 109, 126),
            candle(2, 121, 99, 100),  # breaks the channel low
            candle(3, 130, 108, 125),  # alone after the trim
        ]
        result = run_backtest(base_cfg(stopOnOutOfGrid=True), candles)
        self.assertIn("error", result)
        self.assertEqual(result["pnl"], 0)
        self.assertEqual(result["positionsLong"], 0)


class TestInfiniteBounds(unittest.TestCase):
    """Infinite grids use the candle-window hi/lo +/-1% as bounds."""

    CANDLES = [
        candle(0, 106, 104, 105),
        candle(1, 190, 101, 150),
        candle(2, 200, 110, 180),
        candle(3, 160, 100, 155),
    ]

    def test_build_input_bounds(self):
        engine_input = build_input(base_cfg(gridType="infinite"), self.CANDLES)
        # window hi=200, lo=100 -> 200*1.01=202, 100*0.99=99
        self.assertEqual(engine_input["highPrice"], 202.0)
        self.assertEqual(engine_input["lowPrice"], 99.0)
        result = run_backtest(engine_input, self.CANDLES)
        self.assertEqual(result["gridLevels"][0], 99.0)
        self.assertEqual(result["gridLevels"][-1], 202.0)
        # geometric spacing of ~25% between interior levels
        prices = result["gridLevels"]
        for a, b in zip(prices[:-2], prices[1:-1]):
            self.assertAlmostEqual(b / a, 1.25, places=6)


class _DummyTransport:
    name = "dummy"

    def request(self, method, path, *, body=None, headers=None):
        raise AssertionError("grid transport must not be used by backtest()")

    def close(self):
        pass


class TestClientBacktest(unittest.TestCase):
    """GridClient.backtest: request shape + engine passthrough (hermetic)."""

    class FakeMarket:
        def __init__(self, payload):
            self.payload = payload
            self.calls = []

        def ohlc(self, code, *, timeframe, limit, from_ms):
            self.calls.append({"code": code, "timeframe": timeframe, "limit": limit, "from": from_ms})
            return self.payload

    class FakeMarketGridClient(GridClient):
        def __init__(self, market):
            super().__init__(_DummyTransport())
            self.fake_market = market

        def _market_client(self):
            return self.fake_market

    def _client(self, candles):
        return self.FakeMarketGridClient(self.FakeMarket({"data": candles}))

    def test_url_params_and_summary(self):
        client = self._client(TestOneRoundTripFee.CANDLES)
        result = client.backtest(base_cfg(), timeframe=15, days=31)
        call = client.fake_market.calls[0]
        self.assertEqual(call["code"], "TEST:PAIR")
        self.assertEqual(call["timeframe"], 15)
        self.assertEqual(call["limit"], min(31 * 96, 2976))
        self.assertIsNotNone(call["from"])
        # engine ran on the served candles
        self.assertEqual(result["pnl"], 27.8)
        self.assertEqual(result["summary"]["totalResult"], 27.8)
        self.assertEqual(result["summary"]["positionsLong"], 1)

    def test_limit_cap_and_from_ms(self):
        client = self._client(TestOneRoundTripFee.CANDLES)
        client.backtest(base_cfg(), timeframe=60, days=60, from_ms=12345, limit=500)
        call = client.fake_market.calls[0]
        self.assertEqual(call["limit"], 500)  # explicit limit respected
        self.assertEqual(call["from"], 12345)
        client.backtest(base_cfg(), timeframe=15, days=60)
        self.assertEqual(client.fake_market.calls[1]["limit"], 2976)  # capped

    def test_bare_list_envelope(self):
        # the :2087 ohlc response may also arrive as a bare array
        market = self.FakeMarket(TestOneRoundTripFee.CANDLES)

        class BareClient(GridClient):
            def __init__(self):
                super().__init__(_DummyTransport())

            def _market_client(self):
                return market

        result = BareClient().backtest(base_cfg())
        self.assertEqual(result["pnl"], 27.8)


class TestCliParser(unittest.TestCase):
    def test_backtest_action_parses(self):
        from wtclient.cli import build_parser

        args = build_parser().parse_args(["grid", "backtest", "cfg.json", "--tf", "15", "--days", "31"])
        self.assertEqual(args.action, "backtest")
        self.assertEqual(args.tf, 15)
        self.assertEqual(args.days, 31)
        self.assertEqual(args.transport, "raw")


if __name__ == "__main__":
    unittest.main()
