// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © bahadirsezer

//@version=6
indicator("BS | Buy&Sell Signals With EMA", shorttitle="BS | Buy&Sell Signal With EMA", overlay=true)

// Input for EMA and TP percentages
ema14Length = input.int(14, title="EMA1 Length")
color14 = input.color(color.new(#00ff0c, 0), title="EMA-1 Color")
ema21Length = input.int(21, title="EMA2 Length")
color21 = input.color(color.new(#ff9500, 0), title="EMA-2 Color")
ema55Length = input.int(55, title="EMA3 Length")
color55 = input.color(color.new(color.rgb(0, 42, 255, 50), 0), title="EMA-3 Color")
ema100Length = input.int(100, title="EMA4 Length")
color100 = input.color(color.new(#ff00d47e, 0), title="EMA-4 Color")
ema200Length = input.int(200, title="EMA5 Length")
color200 = input.color(color.new(#ff00007e, 0), title="EMA-5 Color")
tp1PercBuy = input.float(1.1, title="TP1 Percentage (Buy)", minval=0.1, maxval=100)
tp2PercBuy = input.float(5, title="TP2 Percentage (Buy)", minval=0.1, maxval=100)
tp3PercBuy = input.float(10, title="TP3 Percentage (Buy)", minval=0.1, maxval=100)
tp1PercSell = input.float(1.1, title="TP1 Percentage (Sell)", minval=0.1, maxval=100)
tp2PercSell = input.float(3.3, title="TP2 Percentage (Sell)", minval=0.1, maxval=100)
tp3PercSell = input.float(5.5, title="TP3 Percentage (Sell)", minval=0.1, maxval=100)

// Inputs for TP line styles and colors 
tp1StyleBuy = input.string("dashed", title="TP1 Style (Buy)", options=["solid", "dashed", "dotted"]) 
tp2StyleBuy = input.string("dashed", title="TP2 Style (Buy)", options=["solid", "dashed", "dotted"]) 
tp3StyleBuy = input.string("dashed", title="TP3 Style (Buy)", options=["solid", "dashed", "dotted"]) 
tp1StyleSell = input.string("dashed", title="TP1 Style (Sell)", options=["solid", "dashed", "dotted"]) 
tp2StyleSell = input.string("dashed", title="TP2 Style (Sell)", options=["solid", "dashed", "dotted"]) 
tp3StyleSell = input.string("dashed", title="TP3 Style (Sell)", options=["solid", "dashed", "dotted"]) 
tp1ColorBuy = input.color(color.green, title="TP1 Color (Buy)") 
tp2ColorBuy = input.color(color.teal, title="TP2 Color (Buy)") 
tp3ColorBuy = input.color(color.olive, title="TP3 Color (Buy)") 
tp1ColorSell = input.color(color.red, title="TP1 Color (Sell)") 
tp2ColorSell = input.color(color.maroon, title="TP2 Color (Sell)") 
tp3ColorSell = input.color(color.purple, title="TP3 Color (Sell)")

// Inputs for Label colors 
tp1LabelColorBuy = input.color(color.rgb(0, 128, 0, 80), title="TP1 Label Color (Buy)") 
tp2LabelColorBuy = input.color(color.rgb(0, 128, 128, 80), title="TP2 Label Color (Buy)") 
tp3LabelColorBuy = input.color(color.rgb(128, 128, 0, 80), title="TP3 Label Color (Buy)") 
tp1LabelColorSell = input.color(color.rgb(255, 0, 0, 80), title="TP1 Label Color (Sell)") 
tp2LabelColorSell = input.color(color.rgb(128, 0, 0, 80), title="TP2 Label Color (Sell)") 
tp3LabelColorSell = input.color(color.rgb(160, 32, 240, 80), title="TP3 Label Color (Sell)")

// Exponential Moving Averages
ema14 = ta.ema(close, ema14Length)
ema21 = ta.ema(close, ema21Length)
ema55 = ta.ema(close, ema55Length)
ema100 = ta.ema(close, ema100Length)
ema200 = ta.ema(close, ema200Length)


// Plotting Exponential Moving Averages
plot(ema14, title="EMA-1", color=color14)
plot(ema21, title="EMA-2", color=color21)
plot(ema55, title="EMA-3", color=color55)
plot(ema100, title="EMA-4", color=color100)
plot(ema200, title="EMA-5", color=color200)

// Buy and Sell Signals
buySignal = ta.crossover(ema14, ema21)
sellSignal = ta.crossunder(ema14, ema21)

// BUY-SELL Alerts
alertcondition(buySignal, title="Buy Signal", message="Buy signal triggered!")
alertcondition(sellSignal, title="Sell Signal", message="Sell signal triggered!")

// TP Levels Calculation
var float tp1LevelBuy = na
var float tp2LevelBuy = na
var float tp3LevelBuy = na
var float tp1LevelSell = na
var float tp2LevelSell = na
var float tp3LevelSell = na

if (buySignal)
    tp1LevelBuy := close * (1 + tp1PercBuy / 100)
    tp2LevelBuy := close * (1 + tp2PercBuy / 100)
    tp3LevelBuy := close * (1 + tp3PercBuy / 100)

if (sellSignal)
    tp1LevelSell := close * (1 - tp1PercSell / 100)
    tp2LevelSell := close * (1 - tp2PercSell / 100)
    tp3LevelSell := close * (1 - tp3PercSell / 100)

// TP alerts
alertcondition(close >= tp1LevelBuy, title="TP1 Buy", message="TP1 Buy level reached!")
alertcondition(close >= tp2LevelBuy, title="TP2 Buy", message="TP2 Buy level reached!")
alertcondition(close >= tp3LevelBuy, title="TP3 Buy", message="TP3 Buy level reached!")
alertcondition(close <= tp1LevelSell, title="TP1 Sell", message="TP1 Sell level reached!")
alertcondition(close <= tp2LevelSell, title="TP2 Sell", message="TP2 Sell level reached!")
alertcondition(close <= tp3LevelSell, title="TP3 Sell", message="TP3 Sell level reached!")

// Plot Buy and Sell Signals
plotshape(series=buySignal, title="Buy Signal", location=location.belowbar, color=#00897b, style=shape.labelup, text=" BUY ", textcolor=color.white)
plotshape(series=sellSignal, title="Sell Signal", location=location.abovebar, color=color.red, style=shape.labeldown, text=" SELL ", textcolor=color.white)

// TP Lines and Labels for Buy Signal
var line tp1LineBuy = na
var line tp2LineBuy = na
var line tp3LineBuy = na
var label tp1LabelBuy = na
var label tp2LabelBuy = na
var label tp3LabelBuy = na

if (buySignal)
    line.delete(tp1LineBuy)
    line.delete(tp2LineBuy)
    line.delete(tp3LineBuy)
    label.delete(tp1LabelBuy)
    label.delete(tp2LabelBuy)
    label.delete(tp3LabelBuy)
    tp1LineBuy := line.new(x1=bar_index, y1=tp1LevelBuy, x2=bar_index, y2=tp1LevelBuy, color=color.green, width=1, style=line.style_dashed)
    tp2LineBuy := line.new(x1=bar_index, y1=tp2LevelBuy, x2=bar_index, y2=tp2LevelBuy, color=color.teal, width=1, style=line.style_dashed)
    tp3LineBuy := line.new(x1=bar_index, y1=tp3LevelBuy, x2=bar_index, y2=tp3LevelBuy, color=color.olive, width=1, style=line.style_dashed)
    tp1LabelBuy := label.new(x=bar_index, y=tp1LevelBuy, text="BUY TP 1: " + str.tostring(tp1LevelBuy), color=color.rgb(0, 128, 0, 80), textcolor=color.white)
    tp2LabelBuy := label.new(x=bar_index, y=tp2LevelBuy, text="BUY TP 2: " + str.tostring(tp2LevelBuy), color=color.rgb(0, 128, 128, 80), textcolor=color.white)
    tp3LabelBuy := label.new(x=bar_index, y=tp3LevelBuy, text="BUY TP 3: " + str.tostring(tp3LevelBuy), color=color.rgb(128, 128, 0, 80), textcolor=color.white)

// TP Lines and Labels for Sell Signal
var line tp1LineSell = na
var line tp2LineSell = na
var line tp3LineSell = na
var label tp1LabelSell = na
var label tp2LabelSell = na
var label tp3LabelSell = na

if (sellSignal)
    line.delete(tp1LineSell)
    line.delete(tp2LineSell)
    line.delete(tp3LineSell)
    label.delete(tp1LabelSell)
    label.delete(tp2LabelSell)
    label.delete(tp3LabelSell)
    tp1LineSell := line.new(x1=bar_index, y1=tp1LevelSell, x2=bar_index, y2=tp1LevelSell, color=#ff0000, width=1, style=line.style_dashed)
    tp2LineSell := line.new(x1=bar_index, y1=tp2LevelSell, x2=bar_index, y2=tp2LevelSell, color=color.maroon, width=1, style=line.style_dashed)
    tp3LineSell := line.new(x1=bar_index, y1=tp3LevelSell, x2=bar_index, y2=tp3LevelSell, color=color.purple, width=1, style=line.style_dashed)
    tp1LabelSell := label.new(x=bar_index, y=tp1LevelSell, text="SELL TP 1: " + str.tostring(tp1LevelSell), color=color.rgb(255, 0, 0, 80), textcolor=color.white)
    tp2LabelSell := label.new(x=bar_index, y=tp2LevelSell, text="SELL TP 2: " + str.tostring(tp2LevelSell), color=color.rgb(128, 0, 0, 80), textcolor=color.white)
    tp3LabelSell := label.new(x=bar_index, y=tp3LevelSell, text="SELL TP 3: " + str.tostring(tp3LevelSell), color=color.rgb(160, 32, 240, 80), textcolor=color.white)

// Update TP Lines and Labels for Buy Signal
if (not na(tp1LineBuy))
    if (close >= tp1LevelBuy)
        line.set_x2(tp1LineBuy, bar_index + 5)
        label.set_x(tp1LabelBuy, bar_index + 15)
    else
        line.set_x2(tp1LineBuy, bar_index + 5)
        label.set_x(tp1LabelBuy, bar_index + 15)

if (not na(tp2LineBuy))
    if (close >= tp2LevelBuy)
        line.set_x2(tp2LineBuy, bar_index + 5)
        label.set_x(tp2LabelBuy, bar_index + 15)
    else
        line.set_x2(tp2LineBuy, bar_index + 5)
        label.set_x(tp2LabelBuy, bar_index + 15)

if (not na(tp3LineBuy))
    if (close >= tp3LevelBuy)
        line.set_x2(tp3LineBuy, bar_index + 5)
        label.set_x(tp3LabelBuy, bar_index + 15)
    else
        line.set_x2(tp3LineBuy, bar_index + 5)
        label.set_x(tp3LabelBuy, bar_index + 15)

// Update TP Lines and Labels for Sell Signal
if (not na(tp1LineSell))
    if (close <= tp1LevelSell)
        line.set_x2(tp1LineSell, bar_index + 5)
        label.set_x(tp1LabelSell, bar_index + 15)
    else
        line.set_x2(tp1LineSell, bar_index + 5)
        label.set_x(tp1LabelSell, bar_index + 15)

if (not na(tp2LineSell))
    if (close >= tp2LevelSell)
        line.set_x2(tp2LineSell, bar_index + 5)
        label.set_x(tp2LabelSell, bar_index + 15)
    else
        line.set_x2(tp2LineSell, bar_index + 5)
        label.set_x(tp2LabelSell, bar_index + 15)

if (not na(tp3LineSell))
    if (close >= tp3LevelSell)
        line.set_x2(tp3LineSell, bar_index + 5)
        label.set_x(tp3LabelSell, bar_index + 15)
    else
        line.set_x2(tp3LineSell, bar_index + 5)
        label.set_x(tp3LabelSell, bar_index + 15)

    
// Delete TP Lines on opposite signal
if buySignal
    line.delete(tp1LineSell)
    label.delete(tp1LabelSell)
    line.delete(tp2LineSell)
    label.delete(tp2LabelSell)
    line.delete(tp3LineSell)
    label.delete(tp3LabelSell)

// Delete TP Lines on opposite signal
if sellSignal
    line.delete(tp1LineBuy)
    label.delete(tp1LabelBuy)
    line.delete(tp2LineBuy)
    label.delete(tp2LabelBuy)
    line.delete(tp3LineBuy)
    label.delete(tp3LabelBuy)

//Extras

// User-defined inputs
resistanceLevel = input.int(21, title="Resistance Level")
supportLevel = input.int(21, title="Support Level")

// Resistance and Support calculations
var float resistance = na
var float support = na

resistance := ta.highest(high, resistanceLevel)
support := ta.lowest(low, supportLevel)

// Plotting the lines
plot(resistance, title="Resistance", color=color.white, linewidth=1)
plot(support, title="Support", color=color.white, linewidth=1)

// MultiTimeTable
rsiPeriod = input(14, 'Rsi Period', group = 'MULTI TIME SETTINGS')
stochPeriod = input(14, 'Stoch Period', group = 'MULTI TIME SETTINGS')
atrPeriod = input(3, 'ATR Period', group = 'MULTI TIME SETTINGS')
supertrendFactor = input(4, 'Supertrend Factor', group = 'MULTI TIME SETTINGS')
smaPeriod = input(20, 'SMA Period', group = 'MULTI TIME SETTINGS')

tableAlignment = input.string(position.bottom_left, 'Table Alignment', options = [position.bottom_center, position.bottom_left, position.bottom_right, position.middle_center, position.middle_left, position.middle_right, position.top_center, position.top_left, position.top_right])

getValueForTime(timeStr, expr) =>
    request.security(syminfo.ticker, timeStr, expr)

getColor(value) =>
    color.from_gradient(value, 0, 100, color.rgb(0, 255, 0), color.rgb(255, 0, 0))

var indicatorTable = table.new(position = tableAlignment, columns = 8, rows = 5, bgcolor = color.rgb(0, 0, 0, 50), border_width = 1)

table.cell(table_id = indicatorTable, column = 0, row = 1, text = 'RSI', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 0, row = 2, text = 'Stoch', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 0, row = 3, text = 'Supertrend', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 0, row = 4, text = 'SMA (' + str.tostring(smaPeriod) + ')', text_color = color.white, text_size = size.small)

table.cell(table_id = indicatorTable, column = 1, row = 0, text = '1m', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 2, row = 0, text = '5m', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 3, row = 0, text = '15m', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 4, row = 0, text = '1H', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 5, row = 0, text = '4H', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 6, row = 0, text = '1D', text_color = color.white, text_size = size.small)
table.cell(table_id = indicatorTable, column = 7, row = 0, text = '1W', text_color = color.white, text_size = size.small)

makeTableCell(column, row, bgColor, cellText) =>
    table.cell(table_id = indicatorTable, column = column, row = row, text = cellText, bgcolor = bgColor, text_color = color.white, text_size = size.small)

makeRow(row, bgcolors, cellTexts) =>
    for int i = 0 to 6 by 1
        makeTableCell(1 + i, row, array.get(bgcolors, i), array.get(cellTexts, i))

fillArrayWithTime(timeStr, expr, mode, cellTexts, bgColors) =>
    value = getValueForTime(timeStr, expr)

    if mode == 'float'
        array.push(bgColors, getColor(value))
        array.push(cellTexts, str.tostring(math.round(value, 2)))
    else if mode == 'signal'
        array.push(bgColors, getColor(value == 1 ? 100 : value == -1 ? 0 : 50))
        array.push(cellTexts, value == -1 ? 'Buy' : value == 1 ? 'Sell' : 'Neutral')
    [cellTexts, bgColors]

makeMultitimeIndicatorArray(expr, mode) =>
    cellTexts = array.new_string(0, '')
    bgColors = array.new_color(0, color.black)

    fillArrayWithTime('1', expr, mode, cellTexts, bgColors)
    fillArrayWithTime('5', expr, mode, cellTexts, bgColors)
    fillArrayWithTime('15', expr, mode, cellTexts, bgColors)
    fillArrayWithTime('60', expr, mode, cellTexts, bgColors)
    fillArrayWithTime('240', expr, mode, cellTexts, bgColors)
    fillArrayWithTime('1D', expr, mode, cellTexts, bgColors)
    fillArrayWithTime('1W', expr, mode, cellTexts, bgColors)

    [cellTexts, bgColors]

supertrendDirection() =>
    [supertrend, direction] = ta.supertrend(supertrendFactor, atrPeriod)
    direction

[rsiCellTexts, rsiBgColors] = makeMultitimeIndicatorArray(ta.rsi(close, rsiPeriod), 'float')
[stochCellTexts, stochBgColors] = makeMultitimeIndicatorArray(ta.stoch(close, high, low, stochPeriod), 'float')
[supertrendTexts, supertrendBgColors] = makeMultitimeIndicatorArray(supertrendDirection(), 'signal')
[maTrendTexts, maTrendBgColors] = makeMultitimeIndicatorArray(ta.sma(close, 20) > close ? 1 : -1, 'signal')

makeRow(1, rsiBgColors, rsiCellTexts)
makeRow(2, stochBgColors, stochCellTexts)
makeRow(3, supertrendBgColors, supertrendTexts)
makeRow(4, maTrendBgColors, maTrendTexts)

